apiVersion: batch/v1
kind: Job
metadata:
  name: reset-admin-password
  labels:
    app: portfolio
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      restartPolicy: Never
      serviceAccountName: portfolio-workload-identity
      containers:
        - name: reset
          image: us-central1-docker.pkg.dev/kame-457417/kame-house-images/portfolio:latest # {"$imagepolicy": "flux-system:portfolio-image-policy"}
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-lc",
              "npm i --silent bcryptjs@2 prisma@5.22.0 --prefix /tmp && NODE_PATH=/tmp/node_modules node scripts/wait-for-db.js 127.0.0.1 5432 90 && NODE_PATH=/tmp/node_modules /tmp/node_modules/.bin/prisma db push --schema /app/prisma/schema.prisma --skip-generate && NODE_PATH=/tmp/node_modules node scripts/reset-inline.js",
            ]
          volumeMounts:
            - name: reset-script
              mountPath: /app/scripts
              readOnly: true
            - name: prisma-schema
              mountPath: /app/prisma
              readOnly: true
          envFrom:
            - configMapRef:
                name: portfolio-config
            - secretRef:
                name: portfolio-secrets
            - secretRef:
                name: portfolio-db-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          imagePullPolicy: Always
          args:
            - "--structured-logs"
            - "--port=5432"
            - "$(CLOUD_SQL_CONNECTION_NAME)"
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: portfolio-config
                  key: CLOUD_SQL_CONNECTION_NAME
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: reset-script
          configMap:
            name: reset-script
        - name: prisma-schema
          configMap:
            name: prisma-schema
