apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: portfolio-backend-config
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /api/health
