apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: portfolio-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /api/health
