apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: portfolio-cloudsql-sa
spec:
  displayName: "Portfolio Cloud SQL Service Account"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: portfolio-cloudsql-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/kame-457417" # Will be patched by overlay
  bindings:
    - role: roles/cloudsql.client
      members:
        - serviceAccount:portfolio-cloudsql-sa@kame-457417.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: portfolio-cloudsql-key
spec:
  serviceAccountRef:
    name: portfolio-cloudsql-sa
