apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: portfolio-cloudsql-sa
spec:
  displayName: "Portfolio Cloud SQL Service Account"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: portfolio-cloudsql-policy
spec:
  member: serviceAccount:portfolio-cloudsql-sa@kame-457417.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    kind: Project
    external: kame-457417
