apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: hugecat-net-zone
spec:
  dnsName: "hugecat.net."
  description: "DNS zone for hugecat.net domain"
  visibility: "public"
