apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: portfolio-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  sslPolicy: portfolio-ssl-policy
---
apiVersion: networking.gke.io/v1beta1
kind: BackendConfig
metadata:
  name: portfolio-backend-config
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
    negativeCaching: true
    negativeCachingPolicy:
    - code: 404
      ttl: 300
    - code: 410
      ttl: 300
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /api/health
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
