apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: LoadBalancer
  loadBalancerIP: 34.133.54.63
  ports:
    - port: 15021
      targetPort: 15021
      protocol: TCP
    - port: 80
      targetPort: 80
      protocol: HTTP
    - port: 443
      targetPort: 443
      protocol: HTTPS
    - port: 15443
      targetPort: 15443
      protocol: TCP
      name: tls
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
