apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: acme-challenge-override
  namespace: prod
spec:
  hosts:
  - "*"
  gateways:
  - portfolio-gateway
  http:
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver.prod.svc.cluster.local
        port:
          number: 8089
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: portfolio
        port:
          number: 3000
