apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls-cert
  labels:
    app: portfolio
spec:
  secretName: portfolio-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - portfolio.hugecat.net
    - hugecat.net
    - www.hugecat.net
