apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - vpa.yaml
  - hpa.yaml
  - pdb.yaml
  - istio-gateway.yaml
  - istio-virtualservice.yaml
  - service.yaml
  - serviceaccount.yaml
  - auth.yaml
  - certificate-hugecat.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: portfolio-config
    behavior: create
    literals:
      - NODE_ENV=production
      - AZURE_DEPLOYMENT=true
