apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portfolio-network-policy
spec:
  podSelector:
    matchLabels:
      app: portfolio
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {} # placeholder to match istio-system
      ports:
        - protocol: TCP
          port: 3000

  egress:
    - to: [] # Allow egress for Cloud SQL connection, DNS, external APIs
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 3307 # Cloud SQL Auth Proxy default port
