apiVersion: v1
kind: Service
metadata:
  name: portfolio
  annotations:
    cloud.google.com/backend-config: '{"default": "portfolio-backend-config"}'
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  type: ClusterIP
