apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      annotations:
        cloud.google.com/backend-config: '{"default": "portfolio-backend-config"}'
  type: ClusterIP
