apiVersion: v1
kind: Service
metadata:
  name: portfolio
  annotations:
    cloud.google.com/backend-config: '{"default": "portfolio-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: portfolio
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
