apiVersion: v1
kind: Service
metadata:
  name: portfolio
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"portfolio-backend-config"}}'
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
