apiVersion: v1
kind: Service
metadata:
  name: portfolio
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
