apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ssl-certificate.yaml
  - dns-record.yaml

namespace: dev

labels:
  - pairs:
      env: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
    target:
      kind: Deployment
      name: portfolio
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-dev-db
      - op: replace
        path: /spec/settings/diskSize
        value: 10
      - op: replace
        path: /spec/settings/diskType
        value: PD_HDD
    target:
      kind: SQLInstance
      name: portfolio-db-base
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-dev-database
    target:
      kind: SQLDatabase
      name: portfolio-db-database
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-dev-user
    target:
      kind: SQLUser
      name: portfolio-db-user
  - patch: |-
      - op: replace
        path: /spec/resourceRef/external
        value: projects/PROJECT_ID
      - op: replace
        path: /spec/bindings/0/members/0
        value: serviceAccount:portfolio-cloudsql-sa@PROJECT_ID.iam.gserviceaccount.com
    target:
      kind: IAMPolicy
      name: portfolio-cloudsql-policy
  - patch: |-
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: portfolio-dev-ip
      - op: replace
        path: /metadata/annotations/networking.gke.io~1managed-certificates
        value: portfolio-dev-ssl-cert
      - op: replace
        path: /spec/tls/0/hosts
        value: ["portfolio.dev.hugecat.net"]
      - op: replace
        path: /spec/tls/0/secretName
        value: portfolio-dev-ssl-cert
      - op: replace
        path: /spec/rules
        value:
          - host: portfolio.dev.hugecat.net
            http:
              paths:
                - path: /*
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: portfolio
                      port:
                        number: 80
    target:
      kind: Ingress
      name: portfolio-ingress

configMapGenerator:
  - name: portfolio-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - NEXTAUTH_URL=https://portfolio-dev.example.com
      - CLOUD_SQL_CONNECTION_NAME=PROJECT_ID:us-central1:portfolio-dev-db

secretGenerator:
  - name: portfolio-secrets
    behavior: merge
    literals:
      - NEXTAUTH_SECRET=dev-secret-key-change-me
  - name: portfolio-db-secret
    behavior: merge
    literals:
      - DATABASE_URL=postgresql://portfolio-dev-user:dev-password-change-me@localhost:5432/portfolio-dev-database
  - name: portfolio-db-password
    behavior: merge
    literals:
      - password=dev-password-change-me

images:
  - name: portfolio
    newName: us-central1-docker.pkg.dev/kame-457417/kame-house-images/portfolio
    newTag: latest
