apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hugecat-net-cloud-domains
  namespace: config-control
spec:
  name: "hugecat.net."
  type: "NS"
  ttl: 21600
  managedZoneRef:
    name: hugecat-net
  rrdatas:
    - "ns-cloud-c1.googledomains.com."
    - "ns-cloud-c2.googledomains.com."
    - "ns-cloud-c3.googledomains.com."
    - "ns-cloud-c4.googledomains.com."
