apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Strategic-merge patch to increase proxy logging on the app Deployment
  - path: istio-proxy-logging-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: portfolio
  # Ensure Certificate lives in default (ingressgateway ns) so SDS finds Secret
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: portfolio-tls-cert
      namespace: prod
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: default
namespace: prod
labels:
  - pairs:
      env: prod

configMapGenerator:
  - name: portfolio-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://portfolio.hugecat.net
      - CLOUD_SQL_CONNECTION_NAME=kame-457417:us-central1:portfolio-prod-db

secretGenerator:
  - name: portfolio-secrets
    behavior: merge
    literals:
      - NEXTAUTH_SECRET=ifbsSWKAUBAW6ydiqce1-Sy0rxWk6es9W89L7h46DbI
      - ADMIN_EMAIL=admin@hugecat.net
      - ADMIN_PASSWORD=6A71hC5OsUj1CN61
      - ADMIN_NAME=Portfolio Admin
  - name: portfolio-db-secret
    behavior: merge
    literals:
      - DATABASE_URL=postgresql://portfolio-prod-user:k9pm8cGFoNLaZdThKv6gZA@localhost:5432/portfolio-prod-database
  - name: portfolio-db-password
    behavior: merge
    literals:
      - password=k9pm8cGFoNLaZdThKv6gZA
images:
  - name: portfolio
    newName: us-central1-docker.pkg.dev/kame-457417/kame-house-images/portfolio
    newTag: latest

# transformers:
#   - transformers/cert-namespace-patch.yaml
