# Flux CD System Components
# This file contains the core Flux CD components needed for GitOps
# Install these components first: kubectl apply -f k8s/flux-system/gotk-components.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: portfolio-source
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: github-token
  url: https://github.com/ianlintner/portfolio.git
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: portfolio-image-repo
  namespace: flux-system
spec:
  image: us-central1-docker.pkg.dev/kame-457417/kame-house-images/portfolio
  interval: 1m
  secretRef:
    name: gcp-gcr-token
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: portfolio-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-image-repo
  policy:
    semver:
      range: "*"
  filterTags:
    pattern: "^main-[a-f0-9]+-(?P<ts>[0-9]+)$"
    extract: "$ts"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: portfolio-image-updates
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: portfolio-source
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
    push:
      branch: main
  update:
    path: "./k8s"
    strategy: Setters
