apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: portfolio
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ianlintner/portfolio
  ref:
    branch: main
  timeout: 60s
