apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dns-record.yaml

namespace: staging

labels:
  - pairs:
      env: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
    target:
      kind: Deployment
      name: portfolio
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-staging-db
      - op: replace
        path: /spec/settings/diskSize
        value: 20
      - op: replace
        path: /spec/settings/diskType
        value: PD_SSD
    target:
      kind: SQLInstance
      name: portfolio-db-base
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-staging-database
    target:
      kind: SQLDatabase
      name: portfolio-db-database
  - patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-staging-user
    target:
      kind: SQLUser
      name: portfolio-db-user
  - patch: |-
      - op: replace
        path: /spec/resourceRef/external
        value: projects/PROJECT_ID
      - op: replace
        path: /spec/bindings/0/members/0
        value: serviceAccount:portfolio-cloudsql-sa@PROJECT_ID.iam.gserviceaccount.com
    target:
      kind: IAMPolicy
      name: portfolio-cloudsql-policy

configMapGenerator:
  - name: portfolio-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://portfolio-staging.example.com
      - CLOUD_SQL_CONNECTION_NAME=PROJECT_ID:us-central1:portfolio-staging-db

secretGenerator:
  - name: portfolio-secrets
    behavior: merge
    literals:
      - NEXTAUTH_SECRET=staging-secret-key-change-me
  - name: portfolio-db-secret
    behavior: merge
    literals:
      - DATABASE_URL=postgresql://portfolio-staging-user:staging-password-change-me@localhost:5432/portfolio-staging-database
  - name: portfolio-db-password
    behavior: merge
    literals:
      - password=staging-password-change-me

images:
  - name: portfolio
    newName: us-central1-docker.pkg.dev/kame-457417/kame-house-images/portfolio
    newTag: latest
